import { BrandConfig, brandBaseConfigs } from '@repo/theme/brandConfig';

export const brandConfig: BrandConfig = {
  ...brandBaseConfigs.docmorris,
  logo: require('./assets/logo/docmorris.png'),
  ads: [
    require('./assets/ads/ad1.png'),
    require('./assets/ads/ad2.png'),
    require('./assets/ads/ad3.png'),
    require('./assets/ads/ad4.png'),
    require('./assets/ads/ad5.png'),
    require('./assets/ads/ad6.png'),
    require('./assets/ads/ad7.png'),
  ],
  products: [
    {
      id: 0,
      image: require('./assets/products/med1.png'),
      name: 'IBU-ratiopharm 400mg akut Schmerztabletten',
      dosage: '400',
      unit: 'mg',
      type: 'Tabletten',
      rating: 4.7,
      reviewsCount: 2184,
      originalPrice: 5.97,
      discountedPrice: 4.79,
      discountPercent: 20,
      pricePerUnit: '0,24 €/St',
      isFavorite: true,
    },
    {
      id: 1,
      image: require('./assets/products/med2.png'),
      name: 'Thomapyrin Intensiv 20',
      dosage: '20',
      unit: 'St',
      type: 'Tabletten',
      rating: 4.8,
      reviewsCount: 1129,
      originalPrice: 6.99,
      discountedPrice: 5.45,
      discountPercent: 22,
      pricePerUnit: '0,27 €/St',
      isFavorite: false,
    },
    {
      id: 2,
      image: require('./assets/products/med3.png'),
      name: 'Voltaren Schmerzgel forte 2,32 % Gel 180 g',
      dosage: '180',
      unit: 'g',
      type: 'Gel',
      rating: 4.9,
      reviewsCount: 3186,
      originalPrice: 24.99,
      discountedPrice: 19.49,
      discountPercent: 22,
      pricePerUnit: '108,28 €/kg',
      isFavorite: false,
    },
  ],
};
